version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18  
    commands:
      - command
      - command
  pre_build:
    commands:
      - echo Logging into ECR
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=196236753581.dkr.ecr.us-east-1.amazonaws.com/flaskapp-cicd

  build:
    commands:
      - echo Build started on `date` 
      - echo Building the Docker image
      # building docker using repo_uri and tagging it to latest.
      - docker login -u akbaralam96 -p helloworld@1122
      - docker build -t $REPOSITORY_URI:latest . 
      #- docker images
      # changing its tag to add commit has with the tag.
      - docker tag  $REPOSITORY_URI:latest  $REPOSITORY_URI:$IMAGE_TAG
      #- docker images
    
  post_build:
    commands:
      - echo Build Completed on 'date'
      - echo pushing to ECR
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json


artifacts:
  files:
    - imageDetail.json
